server:
  port: 3000
grpc:
  server:
    port: 3002
  client:
    action:
      address: 'static://127.0.0.1:3003'
      negotiation-type: plaintext
    im:
      address: 'static://127.0.0.1:3004'
      negotiation-type: plaintext
    #    market:
    #      address: 'static://127.0.0.1:3005'
    #      negotiation-type: plaintext
    aigc:
      address: 'static://127.0.0.1:3005'
      negotiation-type: plaintext